# Config for deploybot.app
# Docs https://docs.deploybot.app/config/
# Ordered list of Github Deployment environments
deployments:
- name: development
  description: Development deploy
  on_push: true
  on_push_branch: master
    
# Automatically trigger deploy on default branch passing
# on_push: true
#- name: staging
#- name: production
