name: Secret

on:
  push: 
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write
  actions: read
  deployments: write
  
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
            
    runs-on: ${{ matrix.os }}
    
    steps:          
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "Custom Field Check",
            attachments: [{
              "author_name": "8398a7@action-slack", // json
              fallback: 'fallback',
              color: 'good',
              title: 'CI Result',
              text: 'Succeeded',
              fields: [{
                title: 'GCP_DEPLOY_DIR',
                value: '${{ secrets.GCP_DEPLOY_DIR }}',
                short: false
              },
              {
                title: 'GCP_HOST',
                value: '${{ secrets.GCP_HOST }}',
                short: false
              },
              {
                title: 'GCP_INSTANCE_NAME',
                value: '${{ secrets.GCP_INSTANCE_NAME }}',
                short: false
              },
              {
                title: 'GCP_RUNNER_PASSWORD',
                value: '${{ secrets.GCP_RUNNER_PASSWORD }}',
                short: false
              },
              {
                title: 'GCP_SSH_KEY',
                value: '${{ secrets.GCP_SSH_KEY }}',
                short: false
              },
              {
                title: 'GCP_USER',
                value: '${{ secrets.GCP_USER }}',
                short: false
              },
              {
                title: 'GCP_USER_PASSWORD',
                value: '${{ secrets.GCP_USER_PASSWORD }}',
                short: false
              },
              {
                title: 'GCP_WORK_DIR',
                value: '${{ secrets.GCP_WORK_DIR }}',
                short: false
              },
              {
                title: 'GOOGLE_APPLICATION_CREDENTIALS',
                value: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}',
                short: false
              },
              {
                title: 'SLACK_WEBHOOK_URL',
                value: '${{ secrets.SLACK_WEBHOOK_URL }}',
                short: false
              },
              {
                title: 'SLACK_WEBHOOK_URL_2BONO',
                value: '${{ secrets.SLACK_WEBHOOK_URL_2BONO }}',
                short: false
              },
              {
                title: 'SONAR_TOKEN',
                value: '${{ secrets.SONAR_TOKEN }}',
                short: false
              }],
              actions: [{
              }]
            }]
          }        
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2BONO }}
