name: Secret

on:
  push: 
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write
  actions: read
  deployments: write
  
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
            
    runs-on: ${{ matrix.os }}
    
    steps:          
    - name: Checkout
      uses: actions/checkout@v3
      
    - run: |
        echo 'GCP_DEPLOY_DIR\n${{ secrets.GCP_DEPLOY_DIR }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_HOST\n${{ secrets.GCP_HOST }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_INSTANCE_NAME\n${{ secrets.GCP_INSTANCE_NAME }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_RUNNER_PASSWORD\n${{ secrets.GCP_RUNNER_PASSWORD }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_SSH_KEY\n${{ secrets.GCP_SSH_KEY }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_USER\n${{ secrets.GCP_USER }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_USER_PASSWORD\n${{ secrets.GCP_USER_PASSWORD }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GCP_WORK_DIR\n${{ secrets.GCP_WORK_DIR }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'GOOGLE_APPLICATION_CREDENTIALS\n${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'SLACK_WEBHOOK_URL\n${{ secrets.SLACK_WEBHOOK_URL }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'SLACK_WEBHOOK_URL_2BONO\n${{ secrets.SLACK_WEBHOOK_URL_2BONO }}\n\n' >> /home/runner/work/playground/playground/secrets.json
        echo 'SONAR_TOKEN\n${{ secrets.SONAR_TOKEN }}\n\n' >> /home/runner/work/playground/playground/secrets.json

    - name: Artifact Upload Jar
      uses: actions/upload-artifact@v3
      with:
        name: secrets-artifact
        path: /home/runner/work/playground/playground/secrets.json
        retention-days: 1
